-- Criando sequences

CREATE SEQUENCE IF NOT EXISTS SEQ_USUARIO 		INCREMENT 1 START 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_LIVRO         INCREMENT 1 START 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_EMPRESTIMO 	INCREMENT 1 START 1;


-- Criando tabelas

CREATE TABLE IF NOT EXISTS USUARIO (
   ID				INT8 NOT NULL DEFAULT nextval('seq_usuario') PRIMARY KEY,
   NOME				VARCHAR(120) NOT NULL,
   EMAIL			VARCHAR(255) NOT NULL,
   DATA_CADASTRO	VARCHAR(255) NOT NULL,
   TELEFONE			VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS LIVRO (
   ID				    INT8 NOT NULL DEFAULT nextval('seq_livro') PRIMARY KEY,
   TITULO				VARCHAR(60) NOT NULL,
   AUTOR		        VARCHAR(255) NOT NULL,
   ISBN			        INT8 NOT NULL,
   DATA_PUBLICACAO		INT8 NOT null,
   CATEGORIA			INT8 NOT NULL
);

CREATE TABLE IF NOT EXISTS EMPRESTIMO (
   ID				        INT8 NOT NULL DEFAULT nextval('seq_emprestimo') PRIMARY KEY,
   USUARIO_ID				VARCHAR(60) NOT NULL,
   LIVRO_ID		            VARCHAR(255) NOT NULL,
   DATA_EMPRESTIMO			INT8 NOT NULL,
   DATA_DEVOLUCAO			FLOAT8 NOT null,
   STATUS			        VARCHAR(20)
);


-- configurando chaves estrangeiras

ALTER TABLE EMPRESTIMO ADD CONSTRAINT FK_EMPRESTIMO_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO (ID);
ALTER TABLE EMPRESTIMO ADD CONSTRAINT FK_EMPRESTIMO_LIVRO FOREIGN KEY (LIVRO_ID) REFERENCES LIVRO (ID);
